// Code generated by protoc-gen-go from "header.proto"
// DO NOT EDIT!

package main

import proto "code.google.com/p/goprotobuf/proto"
import "math"

// Reference proto and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Header_Compression int32

const (
	Header_NONE   Header_Compression = 0
	Header_ZLIB   Header_Compression = 1
	Header_SNAPPY Header_Compression = 2
)

var Header_Compression_name = map[int32]string{
	0: "NONE",
	1: "ZLIB",
	2: "SNAPPY",
}
var Header_Compression_value = map[string]int32{
	"NONE":   0,
	"ZLIB":   1,
	"SNAPPY": 2,
}

func (x Header_Compression) Enum() *Header_Compression {
	p := new(Header_Compression)
	*p = x
	return p
}
func (x Header_Compression) String() string {
	return proto.EnumName(Header_Compression_name, int32(x))
}

type Header_Type int32

const (
	Header_QUERY    Header_Type = 0
	Header_RESPONSE Header_Type = 1
	Header_EVENT    Header_Type = 2
)

var Header_Type_name = map[int32]string{
	0: "QUERY",
	1: "RESPONSE",
	2: "EVENT",
}
var Header_Type_value = map[string]int32{
	"QUERY":    0,
	"RESPONSE": 1,
	"EVENT":    2,
}

func (x Header_Type) Enum() *Header_Type {
	p := new(Header_Type)
	*p = x
	return p
}
func (x Header_Type) String() string {
	return proto.EnumName(Header_Type_name, int32(x))
}

type Header struct {
	Id               *uint32             `protobuf:"varint,1,opt,name=id,def=0" json:"id,omitempty"`
	Path             []byte              `protobuf:"bytes,2,req,name=path" json:"path,omitempty"`
	Compression      *Header_Compression `protobuf:"varint,3,opt,name=compression,enum=main.Header_Compression,def=0" json:"compression,omitempty"`
	Type             *Header_Type        `protobuf:"varint,4,opt,name=type,enum=main.Header_Type,def=2" json:"type,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (this *Header) Reset()         { *this = Header{} }
func (this *Header) String() string { return proto.CompactTextString(this) }
func (*Header) ProtoMessage()       {}

const Default_Header_Id uint32 = 0
const Default_Header_Compression Header_Compression = Header_NONE
const Default_Header_Type Header_Type = Header_EVENT

func (this *Header) GetId() uint32 {
	if this != nil && this.Id != nil {
		return *this.Id
	}
	return Default_Header_Id
}

func (this *Header) GetPath() []byte {
	if this != nil {
		return this.Path
	}
	return nil
}

func (this *Header) GetCompression() Header_Compression {
	if this != nil && this.Compression != nil {
		return *this.Compression
	}
	return Default_Header_Compression
}

func (this *Header) GetType() Header_Type {
	if this != nil && this.Type != nil {
		return *this.Type
	}
	return Default_Header_Type
}

func init() {
	proto.RegisterEnum("main.Header_Compression", Header_Compression_name, Header_Compression_value)
	proto.RegisterEnum("main.Header_Type", Header_Type_name, Header_Type_value)
}
